name: slowpick
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Firebase 관련 패키지
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  
  # UI 및 이미지 관련 패키지
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - images/
    - images/brand_logo/
    - images/main_icon/
    - images/home/
    - images/comment_menu/
    - images/myPage/

  
  fonts:
    - family: KoPubDotum
      fonts:
        - asset: fonts/KoPubDotumLight.ttf
          weight: 300
        - asset: fonts/KoPubDotumMedium.ttf
          weight: 500
        - asset: fonts/KoPubDotumBold.ttf
          weight: 700
    - family: Clipartkorea
      fonts:
        - asset: fonts/클립아트코리아_Light.ttf
          weight: 300
        - asset: fonts/클립아트코리아_Regular.ttf
          weight: 400
        - asset: fonts/클립아트코리아_Medium.ttf
          weight: 500
        - asset: fonts/클립아트코리아_Bold.ttf
          weight: 700
    

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
