// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTHWQRayWiJsYOabO2sqGlcqG1UVrXvU',
    appId: '1:1097183462743:web:70fc0579d4f1f42d9caa12',
    messagingSenderId: '1097183462743',
    projectId: 'slowpick-ebc24',
    authDomain: 'slowpick-ebc24.firebaseapp.com',
    storageBucket: 'slowpick-ebc24.firebasestorage.app',
    measurementId: 'G-W3WN7ZLK46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvjWrD7oWblsbdGK8Xk5fAcG5Fxm70DQ',
    appId: '1:1097183462743:android:5d6992741254e92e9caa12',
    messagingSenderId: '1097183462743',
    projectId: 'slowpick-ebc24',
    storageBucket: 'slowpick-ebc24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMXRsvbLZ4GPb_l7IM50EooXAAo9v6Vw',
    appId: '1:1097183462743:ios:f0d20a2fcfdc7d089caa12',
    messagingSenderId: '1097183462743',
    projectId: 'slowpick-ebc24',
    storageBucket: 'slowpick-ebc24.firebasestorage.app',
    iosBundleId: 'com.example.slowpick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMMXRsvbLZ4GPb_l7IM50EooXAAo9v6Vw',
    appId: '1:1097183462743:ios:f0d20a2fcfdc7d089caa12',
    messagingSenderId: '1097183462743',
    projectId: 'slowpick-ebc24',
    storageBucket: 'slowpick-ebc24.firebasestorage.app',
    iosBundleId: 'com.example.slowpick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzTHWQRayWiJsYOabO2sqGlcqG1UVrXvU',
    appId: '1:1097183462743:web:d4492324902160969caa12',
    messagingSenderId: '1097183462743',
    projectId: 'slowpick-ebc24',
    authDomain: 'slowpick-ebc24.firebaseapp.com',
    storageBucket: 'slowpick-ebc24.firebasestorage.app',
    measurementId: 'G-V64L5CEDCX',
  );
}
